create table if not exists public.part_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null,
  song_id text not null,
  part text not null,
  display_name text not null
);
alter table public.part_requests enable row level security;

drop policy if exists "part_requests_select_authenticated" on public.part_requests;
create policy "part_requests_select_authenticated" on public.part_requests
for select to authenticated using (true);

drop policy if exists "part_requests_insert_own" on public.part_requests;
create policy "part_requests_insert_own" on public.part_requests
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "part_requests_delete_own" on public.part_requests;
create policy "part_requests_delete_own" on public.part_requests
for delete to authenticated using (auth.uid() = user_id);

create unique index if not exists part_requests_unique
on public.part_requests(user_id, song_id, part);
